### ISSUE TITLE
Issue with subsequence build

### ISSUE THREAD

**Issue by ThinhTT84** [bobril/bbcore#11]
We have small issue with sub-sequence build when using BB2. The 1st build is OK, web can load normal. But after that if we change anything the sub sequence build has problem. The build itself seems OK, but web can't be loaded. A lot of error in LocalRunner because of file missing.

```
2018-03-21 14:38:40.018 ERROR 3 4055 FileSystemFileProvider Failed to read file from drive. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\GMC\inspirecloud\WebBobwai\dist\node_modules\bobwai--icon\assets\checkbox-unchecked-small.png'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at Gmc.Cloud.Infrastructure.Server.FileSystemFileProvider.<Get>d__3.MoveNext() in C:\GMC\inspirecloud\paket-files\gitlab.gmc.net\skymamba\skymamba\Packages\Infrastructure\src\Infrastructure\Server\IFileProvider.cs:line 65    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at Gmc.Cloud.Infrastructure.Server.FileSystemFileProvider.<Get>d__3.MoveNext() in C:\GMC\inspirecloud\paket-files\gitlab.gmc.net\skymamba\skymamba\Packages\Infrastructure\src\Infrastructure\Server\IFileProvider.cs:line 65
```

**Comment by saryn** [comment]
File watcher is not working - bbcore does not detect file changes so rebuild is not started.
Issue occurs on more PCs.

**Comment by Bobris** [comment]
That's issue stealing :-) But because original issue is probably solved now anyway (@ThinhTT84 am I right?). We can continue with problem with file watcher.
