### ISSUE TITLE
bbcore don´t work in docker 

### ISSUE THREAD

**Issue by LongerP** [bobril/bbcore#34]
bbcore is not working in docker (windows and linux hosts)

Docker:
```
FROM node:latest

# Global install yarn package manager
RUN apt-get update && apt-get install -y curl apt-transport-https && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && apt-get install -y yarn

RUN yarn global add bobril-build

# Enable detection of running in a container
ENV DOTNET_RUNNING_IN_CONTAINER=true

WORKDIR /workspace

EXPOSE 80 443 8080
```

Output:
```
Updating latest version information from Github
Downloading linux-x64.zip from 0.51.1
Unzipping
Bobril-build core running /root/.bbcore/0.51.1

Unhandled Exception: System.Exception: Cannot find empty port to be allowed to listen on. Started on 8080
   at Lib.WebServer.WebServerHost.Start() in c:\Research\bbcore\Lib\WebServer\WebServerHost.cs:line 80
   at Lib.Composition.Composition.StartWebServer(Int32 port, Boolean bindToAny) in c:\Research\bbcore\Lib\Composition\Composition.cs:line 686
   at Lib.Composition.Composition.RunInteractive(CommonInteractiveCommand command) in c:\Research\bbcore\Lib\Composition\Composition.cs:line 610
   at bb.Program.Main(String[] args) in c:\Research\bbcore\bb\Program.cs:line 10
```

**Comment by LongerP** [comment]
Sakra teď koukám že už na dokerizaci děláš.
